export const achievementsData = [
  {
    id: 1,
    achievementName: "Первая книга",
    description: "Прочитана первая книга",
    imageUrl: "/images/first_book.png",
    condition: "Прочитано 1 книга",
    conditionKey: "read_1_book",
    type: "progress",
    isActive: true,
    points: 10,
  },
  {
    id: 2,
    achievementName: "10 книг",
    description: "Прочитано 10 книг",
    imageUrl: "/images/10_books.png",
    condition: "Прочитано 10 книг",
    conditionKey: "read_10_books",
    type: "progress",
    isActive: true,
    points: 50,
  },
  {
    id: 3,
    achievementName: "Читатель года",
    description: "Чтение книг в течение целого года",
    imageUrl: "/images/year_reader.png",
    condition: "Чтение книг на протяжении года",
    conditionKey: "year_reading",
    type: "milestone",
    isActive: true,
    points: 100,
  },
  {
    id: 4,
    achievementName: "Покоритель жанров",
    description: "Прочитаны книги из всех жанров",
    imageUrl: "/images/genre_master.png",
    condition: "Прочитаны книги из всех жанров",
    conditionKey: "read_all_genres",
    type: "milestone",
    isActive: true,
    points: 75,
  },
  {
    id: 5,
    achievementName: "Переводчик",
    description: "Переведена книга на другой язык",
    imageUrl: "/images/translator.png",
    condition: "Переведена хотя бы одна книга",
    conditionKey: "translated_book",
    type: "achievement",
    isActive: true,
    points: 150,
  },
  {
    id: 6,
    achievementName: "Рецензент",
    description: "Написан первый отзыв о книге",
    imageUrl: "/images/reviewer.png",
    condition: "Написан первый отзыв о книге",
    conditionKey: "first_review",
    type: "achievement",
    isActive: true,
    points: 20,
  },
  {
    id: 7,
    achievementName: "Друзья книги",
    description: "Приглашено 5 друзей на сайт",
    imageUrl: "/images/friends_book.png",
    condition: "Приглашены 5 друзей",
    conditionKey: "invite_5_friends",
    type: "social",
    isActive: true,
    points: 30,
  },
  {
    id: 8,
    achievementName: "Книжный блогер",
    description: "Создан личный блог на сайте",
    imageUrl: "/images/book_blogger.png",
    condition: "Создан и опубликован первый пост в блоге",
    conditionKey: "first_blog_post",
    type: "achievement",
    isActive: true,
    points: 50,
  },
  {
    id: 9,
    achievementName: "Супер читатель",
    description: "Прочитано 50 книг",
    imageUrl: "/images/super_reader.png",
    condition: "Прочитано 50 книг",
    conditionKey: "read_50_books",
    type: "progress",
    isActive: true,
    points: 200,
  },
  {
    id: 10,
    achievementName: "Все о книгах",
    description: "Прочитаны все доступные книги в базе данных",
    imageUrl: "/images/all_books.png",
    condition: "Прочитаны все книги в базе",
    conditionKey: "read_all_books",
    type: "milestone",
    isActive: false,
    points: 500,
  },
];
