import { DbAuthor } from "../../types/author";

export const authorsSeedData: DbAuthor[] = [
  {
    id: 1,
    firstName: "Terry",
    middleName: null,
    lastName: "Pratchett",
    penName: null,
    bio: "English author of fantasy novels, best known for the Discworld series, a humorous and satirical take on fantasy tropes.",
    gender: "male",
    birthDate: new Date("1948-04-28"),
    deathDate: new Date("2015-03-12"),
    status: "deceased",
    country: "United Kingdom",
    languageCode: "en",
    photoUrl: "https://example.com/photos/terry-pratchett.jpg",
    website: "https://www.terrypratchettbooks.com",
    twitter: "terryandrob",
    facebook: null,
    instagram: null,
    linkedin: null,
    email: null,
    slug: "terry-pratchett",
    createdAt: new Date("2023-01-01T10:00:00Z"),
    updatedAt: new Date("2023-01-01T10:00:00Z"),
  },
  {
    id: 2,
    firstName: "Neil",
    middleName: null,
    lastName: "Gaiman",
    penName: null,
    bio: "English author known for works like American Gods, Coraline, and The Sandman, blending mythology, fantasy, and horror.",
    gender: "male",
    birthDate: new Date("1960-11-10"),
    deathDate: null,
    status: "active",
    country: "United Kingdom",
    languageCode: "en",
    photoUrl: "https://example.com/photos/neil-gaiman.jpg",
    website: "https://www.neilgaiman.com",
    twitter: "neilhimself",
    facebook: "neilgaiman",
    instagram: "neilhimself",
    linkedin: null,
    email: "contact@neilgaiman.com",
    slug: "neil-gaiman",
    createdAt: new Date("2023-01-02T12:00:00Z"),
    updatedAt: new Date("2023-01-02T12:00:00Z"),
  },
  {
    id: 3,
    firstName: "Stephen",
    middleName: "Edwin",
    lastName: "King",
    penName: "Richard Bachman",
    bio: "American author of horror, suspense, and fantasy novels, including The Shining, It, and The Dark Tower series.",
    gender: "male",
    birthDate: new Date("1947-09-21"),
    deathDate: null,
    status: "active",
    country: "United States",
    languageCode: "en",
    photoUrl: "https://example.com/photos/stephen-king.jpg",
    website: "https://www.stephenking.com",
    twitter: "StephenKing",
    facebook: "StephenKing",
    instagram: "stephenkingauthor",
    linkedin: null,
    email: null,
    slug: "stephen-king",
    createdAt: new Date("2023-01-03T14:00:00Z"),
    updatedAt: new Date("2023-01-03T14:00:00Z"),
  },
  {
    id: 4,
    firstName: "Svetlana",
    middleName: null,
    lastName: "Martynchik",
    penName: "Max Frei",
    bio: "Russian author known for the Echo Chronicles, a fantasy series blending detective and magical elements under the pseudonym Max Frei.",
    gender: "female",
    birthDate: new Date("1965-02-17"),
    deathDate: null,
    status: "active",
    country: "Russia",
    languageCode: "ru",
    photoUrl: "https://example.com/photos/max-frei.jpg",
    website: null,
    twitter: null,
    facebook: null,
    instagram: null,
    linkedin: null,
    email: null,
    slug: "max-frei",
    createdAt: new Date("2023-01-04T16:00:00Z"),
    updatedAt: new Date("2023-01-04T16:00:00Z"),
  },
  {
    id: 5,
    firstName: "Joanne",
    middleName: null,
    lastName: "Rowling",
    penName: "J.K. Rowling",
    bio: "British author of the Harry Potter series, which became a global phenomenon, and writes crime fiction as Robert Galbraith.",
    gender: "female",
    birthDate: new Date("1965-07-31"),
    deathDate: null,
    status: "active",
    country: "United Kingdom",
    languageCode: "en",
    photoUrl: "https://example.com/photos/jk-rowling.jpg",
    website: "https://www.jkrowling.com",
    twitter: "jk_rowling",
    facebook: "jkrowling",
    instagram: "jkrowling_official",
    linkedin: null,
    email: null,
    slug: "jk-rowling",
    createdAt: new Date("2023-01-05T09:00:00Z"),
    updatedAt: new Date("2023-01-05T09:00:00Z"),
  },
  {
    id: 6,
    firstName: "Andrzej",
    middleName: null,
    lastName: "Sapkowski",
    penName: null,
    bio: "Polish fantasy writer, best known for The Witcher series, which inspired video games and a Netflix show.",
    gender: "male",
    birthDate: new Date("1948-06-21"),
    deathDate: null,
    status: "active",
    country: "Poland",
    languageCode: "pl",
    photoUrl: "https://example.com/photos/andrzej-sapkowski.jpg",
    website: null,
    twitter: null,
    facebook: null,
    instagram: null,
    linkedin: null,
    email: null,
    slug: "andrzej-sapkowski",
    createdAt: new Date("2023-01-06T11:00:00Z"),
    updatedAt: new Date("2023-01-06T11:00:00Z"),
  },
];