import { DbAuthor } from "../../types/author";

export const authorsSeedData: DbAuthor[] = [
  {
    id: 1,
    firstName: "Terry",
    middleName: null,
    lastName: "Pratchett",
    penName: null,
    bio: "English author of fantasy novels, best known for the Discworld series, a humorous and satirical take on fantasy tropes.",
    gender: "male",
    birthDate: new Date("1948-04-28"),
    deathDate: new Date("2015-03-12"),
    status: "deceased",
    country: "United Kingdom",
    languageCode: "en",
    photoUrl: "https://cdn.britannica.com/22/182022-050-C682CF9C/Terry-Pratchett-2011.jpg",
    website: "https://www.terrypratchettbooks.com",
    twitter: "terryandrob",
    facebook: null,
    instagram: null,
    linkedin: null,
    email: null,
    slug: "terry-pratchett",
    createdAt: new Date("2023-01-01T10:00:00Z"),
    updatedAt: new Date("2023-01-01T10:00:00Z"),
  },
  {
    id: 2,
    firstName: "Neil",
    middleName: null,
    lastName: "Gaiman",
    penName: null,
    bio: "English author known for works like American Gods, Coraline, and The Sandman, blending mythology, fantasy, and horror.",
    gender: "male",
    birthDate: new Date("1960-11-10"),
    deathDate: null,
    status: "active",
    country: "United Kingdom",
    languageCode: "en",
    photoUrl: "https://media.npr.org/assets/img/2013/05/16/gaimanauthorphoto_custom-8bd0a2754d8e31e798c37fbd2eb0a99d1bfc3550.jpg",
    website: "https://www.neilgaiman.com",
    twitter: "neilhimself",
    facebook: "neilgaiman",
    instagram: "neilhimself",
    linkedin: null,
    email: "contact@neilgaiman.com",
    slug: "neil-gaiman",
    createdAt: new Date("2023-01-02T12:00:00Z"),
    updatedAt: new Date("2023-01-02T12:00:00Z"),
  },
  {
    id: 3,
    firstName: "Stephen",
    middleName: "Edwin",
    lastName: "King",
    penName: "Richard Bachman",
    bio: "American author of horror, suspense, and fantasy novels, including The Shining, It, and The Dark Tower series.",
    gender: "male",
    birthDate: new Date("1947-09-21"),
    deathDate: null,
    status: "active",
    country: "United States",
    languageCode: "en",
    photoUrl: "https://static.wikia.nocookie.net/stephenking/images/9/92/%D0%A1%D1%82%D0%B8%D0%B2%D0%B5%D0%BD_%D0%9A%D0%B8%D0%BD%D0%B3.jpg/revision/latest?cb=20170924114320&path-prefix=ru",
    website: "https://www.stephenking.com",
    twitter: "StephenKing",
    facebook: "StephenKing",
    instagram: "stephenkingauthor",
    linkedin: null,
    email: null,
    slug: "stephen-king",
    createdAt: new Date("2023-01-03T14:00:00Z"),
    updatedAt: new Date("2023-01-03T14:00:00Z"),
  },
  {
    id: 4,
    firstName: "Svetlana",
    middleName: null,
    lastName: "Martynchik",
    penName: "Max Frei",
    bio: "Russian author known for the Echo Chronicles, a fantasy series blending detective and magical elements under the pseudonym Max Frei.",
    gender: "female",
    birthDate: new Date("1965-02-17"),
    deathDate: null,
    status: "active",
    country: "Russia",
    languageCode: "ru",
    photoUrl: "https://static.yakaboo.ua/media/entity/author/1/_/1_85.jpg",
    website: null,
    twitter: null,
    facebook: null,
    instagram: null,
    linkedin: null,
    email: null,
    slug: "max-frei",
    createdAt: new Date("2023-01-04T16:00:00Z"),
    updatedAt: new Date("2023-01-04T16:00:00Z"),
  },
  {
    id: 5,
    firstName: "Joanne",
    middleName: null,
    lastName: "Rowling",
    penName: "J.K. Rowling",
    bio: "British author of the Harry Potter series, which became a global phenomenon, and writes crime fiction as Robert Galbraith.",
    gender: "female",
    birthDate: new Date("1965-07-31"),
    deathDate: null,
    status: "active",
    country: "United Kingdom",
    languageCode: "en",
    photoUrl: "https://hips.hearstapps.com/hmg-prod/images/gettyimages-1061157246.jpg?crop=1xw:1.0xh;center,top&resize=640:*",
    website: "https://www.jkrowling.com",
    twitter: "jk_rowling",
    facebook: "jkrowling",
    instagram: "jkrowling_official",
    linkedin: null,
    email: null,
    slug: "jk-rowling",
    createdAt: new Date("2023-01-05T09:00:00Z"),
    updatedAt: new Date("2023-01-05T09:00:00Z"),
  },
  {
    id: 6,
    firstName: "Andrzej",
    middleName: null,
    lastName: "Sapkowski",
    penName: null,
    bio: "Polish fantasy writer, best known for The Witcher series, which inspired video games and a Netflix show.",
    gender: "male",
    birthDate: new Date("1948-06-21"),
    deathDate: null,
    status: "active",
    country: "Poland",
    languageCode: "pl",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Andrzej_Sapkowski_-_Lucca_Comics_%26_Games_2015.JPG/250px-Andrzej_Sapkowski_-_Lucca_Comics_%26_Games_2015.JPG",
    website: null,
    twitter: null,
    facebook: null,
    instagram: null,
    linkedin: null,
    email: null,
    slug: "andrzej-sapkowski",
    createdAt: new Date("2023-01-06T11:00:00Z"),
    updatedAt: new Date("2023-01-06T11:00:00Z"),
  },
];