export const booksData = [
  // Discworld: Death (Terry Pratchett)
  {
    id: 1,
    title: "Mort",
    originalTitle: null,
    description: "Death takes on an apprentice, Mort, who struggles with the responsibilities of guiding souls to the afterlife in the Discworld universe.",
    slug: "mort",
    isbn: "9780061020681",
    languageCode: "en",
    ageLimit: 12,
    pageCount: 243,
    publisher: "Corgi Books",
    publishedDate: "1987-11-12",
    seriesIndex: 1,
    seriesId: 1,
    rating: 4.5,
    totalReviews: 1200,
    coverUrl: "https://example.com/covers/mort.jpg",
    previewUrl: null,
    downloadUrl: null,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-01T10:00:00Z"),
    updatedAt: new Date("2023-01-01T10:00:00Z"),
    createdByUserId: null,
  },
  {
    id: 2,
    title: "Reaper Man",
    originalTitle: null,
    description: "Death is forced into retirement, causing chaos as the undead linger, while he explores life as a farmhand named Bill Door.",
    slug: "reaper-man",
    isbn: "9780552137034",
    languageCode: "en",
    ageLimit: 12,
    pageCount: 288,
    publisher: "Corgi Books",
    publishedDate: "1991-05-09",
    seriesIndex: 2,
    seriesId: 1,
    rating: 4.6,
    totalReviews: 1100,
    coverUrl: "https://example.com/covers/reaper-man.jpg",
    previewUrl: null,
    downloadUrl: null,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-01T10:10:00Z"),
    updatedAt: new Date("2023-01-01T10:10:00Z"),
    createdByUserId: null,
  },
  {
    id: 3,
    title: "Soul Music",
    originalTitle: null,
    description: "Death's granddaughter Susan must save the Discworld when rock music with a magical twist threatens to take over.",
    slug: "soul-music",
    isbn: "9780552140294",
    languageCode: "en",
    ageLimit: 12,
    pageCount: 384,
    publisher: "Corgi Books",
    publishedDate: "1994-05-19",
    seriesIndex: 3,
    seriesId: 1,
    rating: 4.4,
    totalReviews: 1000,
    coverUrl: "https://example.com/covers/soul-music.jpg",
    previewUrl: null,
    downloadUrl: null,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-01T10:20:00Z"),
    updatedAt: new Date("2023-01-01T10:20:00Z"),
    createdByUserId: null,
  },
  // Discworld: Witches (Terry Pratchett)
  {
    id: 4,
    title: "Equal Rites",
    originalTitle: null,
    description: "The first Discworld book featuring Granny Weatherwax, where a young girl, Eskarina, inherits a wizard’s staff and challenges magical traditions.",
    slug: "equal-rites",
    isbn: "9780060855901",
    languageCode: "en",
    ageLimit: 12,
    pageCount: 240,
    publisher: "Corgi Books",
    publishedDate: "1987-01-15",
    seriesIndex: 1,
    seriesId: 2,
    rating: 4.3,
    totalReviews: 950,
    coverUrl: "https://example.com/covers/equal-rites.jpg",
    previewUrl: null,
    downloadUrl: null,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-02T12:00:00Z"),
    updatedAt: new Date("2023-01-02T12:00:00Z"),
    createdByUserId: null,
  },
  {
    id: 5,
    title: "Wyrd Sisters",
    originalTitle: null,
    description: "Granny Weatherwax, Nanny Ogg, and Magrat Garlick meddle in royal politics to restore the rightful king in a Shakespeare-inspired tale.",
    slug: "wyrd-sisters",
    isbn: "9780552134606",
    languageCode: "en",
    ageLimit: 12,
    pageCount: 265,
    publisher: "Corgi Books",
    publishedDate: "1988-11-10",
    seriesIndex: 2,
    seriesId: 2,
    rating: 4.5,
    totalReviews: 1050,
    coverUrl: "https://example.com/covers/wyrd-sisters.jpg",
    previewUrl: null,
    downloadUrl: null,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-02T12:10:00Z"),
    updatedAt: new Date("2023-01-02T12:10:00Z"),
    createdByUserId: null,
  },
  {
    id: 6,
    title: "Witches Abroad",
    originalTitle: null,
    description: "The Lancre witches travel to a faraway land to prevent a fairy-tale ending, battling the power of stories and godmothers.",
    slug: "witches-abroad",
    isbn: "9780552134651",
    languageCode: "en",
    ageLimit: 12,
    pageCount: 288,
    publisher: "Corgi Books",
    publishedDate: "1991-11-14",
    seriesIndex: 3,
    seriesId: 2,
    rating: 4.6,
    totalReviews: 1000,
    coverUrl: "https://example.com/covers/witches-abroad.jpg",
    previewUrl: null,
    downloadUrl: null,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-02T12:20:00Z"),
    updatedAt: new Date("2023-01-02T12:20:00Z"),
    createdByUserId: null,
  },
  // The Sandman (Neil Gaiman)
  {
    id: 7,
    title: "The Sandman: Preludes & Nocturnes",
    originalTitle: null,
    description: "The first volume of The Sandman, where Dream is captured and must reclaim his kingdom, exploring themes of power and myth.",
    slug: "sandman-preludes-nocturnes",
    isbn: "9781401225759",
    languageCode: "en",
    ageLimit: 16,
    pageCount: 240,
    publisher: "Vertigo",
    publishedDate: "1988-12-01",
    seriesIndex: 1,
    seriesId: 3,
    rating: 4.7,
    totalReviews: 1500,
    coverUrl: "https://example.com/covers/sandman-preludes.jpg",
    previewUrl: null,
    downloadUrl: null,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-03T14:00:00Z"),
    updatedAt: new Date("2023-01-03T14:00:00Z"),
    createdByUserId: null,
  },
  {
    id: 8,
    title: "The Sandman: The Doll's House",
    originalTitle: null,
    description: "Dream tracks a rogue dream vortex, Rose Walker, while unraveling mysteries of his creations in the second Sandman volume.",
    slug: "sandman-dolls-house",
    isbn: "9781401227999",
    languageCode: "en",
    ageLimit: 16,
    pageCount: 232,
    publisher: "Vertigo",
    publishedDate: "1989-09-01",
    seriesIndex: 2,
    seriesId: 3,
    rating: 4.8,
    totalReviews: 1400,
    coverUrl: "https://example.com/covers/sandman-dolls-house.jpg",
    previewUrl: null,
    downloadUrl: null,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-03T14:10:00Z"),
    updatedAt: new Date("2023-01-03T14:10:00Z"),
    createdByUserId: null,
  },
  // The Dark Tower (Stephen King)
  {
    id: 9,
    title: "The Gunslinger",
    originalTitle: null,
    description: "The first book in The Dark Tower series, following Roland Deschain as he pursues the Man in Black across a desolate world.",
    slug: "the-gunslinger",
    isbn: "9780452284692",
    languageCode: "en",
    ageLimit: 14,
    pageCount: 231,
    publisher: "Signet",
    publishedDate: "1982-06-10",
    seriesIndex: 1,
    seriesId: 4,
    rating: 4.4,
    totalReviews: 2000,
    coverUrl: "https://example.com/covers/the-gunslinger.jpg",
    previewUrl: null,
    downloadUrl: null,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-04T16:00:00Z"),
    updatedAt: new Date("2023-01-04T16:00:00Z"),
    createdByUserId: null,
  },
  {
    id: 10,
    title: "The Drawing of the Three",
    originalTitle: null,
    description: "Roland gathers companions, Eddie and Odetta, from different times, facing dangers in his quest for the Dark Tower.",
    slug: "drawing-of-the-three",
    isbn: "9780452279612",
    languageCode: "en",
    ageLimit: 14,
    pageCount: 406,
    publisher: "Signet",
    publishedDate: "1987-05-01",
    seriesIndex: 2,
    seriesId: 4,
    rating: 4.5,
    totalReviews: 1800,
    coverUrl: "https://example.com/covers/drawing-of-the-three.jpg",
    previewUrl: null,
    downloadUrl: null,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-04T16:10:00Z"),
    updatedAt: new Date("2023-01-04T16:10:00Z"),
    createdByUserId: null,
  },
  // Echo Chronicles (Max Frei)
  {
    id: 11,
    title: "The Stranger",
    originalTitle: "Чужак",
    description: "The first book in the Echo Chronicles, where Sir Max arrives in the magical city of Echo and begins solving supernatural mysteries.",
    slug: "the-stranger",
    isbn: "9785170881239",
    languageCode: "ru",
    ageLimit: 14,
    pageCount: 416,
    publisher: "AST",
    publishedDate: "1996-01-01",
    seriesIndex: 1,
    seriesId: 5,
    rating: 4.5,
    totalReviews: 800,
    coverUrl: "https://example.com/covers/the-stranger.jpg",
    previewUrl: null,
    downloadUrl: null,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-05T09:00:00Z"),
    updatedAt: new Date("2023-01-05T09:00:00Z"),
    createdByUserId: null,
  },
  {
    id: 12,
    title: "The Volunteers of Eternity",
    originalTitle: "Волонтёры вечности",
    description: "Sir Max continues his adventures in Echo, uncovering secrets of the magical world and battling mysterious foes.",
    slug: "volunteers-of-eternity",
    isbn: "9785170881246",
    languageCode: "ru",
    ageLimit: 14,
    pageCount: 384,
    publisher: "AST",
    publishedDate: "1997-01-01",
    seriesIndex: 2,
    seriesId: 5,
    rating: 4.6,
    totalReviews: 750,
    coverUrl: "https://example.com/covers/volunteers-of-eternity.jpg",
    previewUrl: null,
    downloadUrl: null,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-05T09:10:00Z"),
    updatedAt: new Date("2023-01-05T09:10:00Z"),
    createdByUserId: null,
  },
  // Harry Potter (J.K. Rowling)
  {
    id: 13,
    title: "Harry Potter and the Philosopher's Stone",
    originalTitle: null,
    description: "The first book in the Harry Potter series, where young Harry discovers he’s a wizard and begins his journey at Hogwarts.",
    slug: "harry-potter-philosophers-stone",
    isbn: "9780747532699",
    languageCode: "en",
    ageLimit: 10,
    pageCount: 223,
    publisher: "Bloomsbury",
    publishedDate: "1997-06-26",
    seriesIndex: 1,
    seriesId: 6,
    rating: 4.8,
    totalReviews: 5000,
    coverUrl: "https://example.com/covers/harry-potter-1.jpg",
    previewUrl: null,
    downloadUrl: null,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-06T11:00:00Z"),
    updatedAt: new Date("2023-01-06T11:00:00Z"),
    createdByUserId: null,
  },
  {
    id: 14,
    title: "Harry Potter and the Chamber of Secrets",
    originalTitle: null,
    description: "Harry returns to Hogwarts, facing mysterious attacks linked to the Chamber of Secrets and a dangerous magical creature.",
    slug: "harry-potter-chamber-of-secrets",
    isbn: "9780747538493",
    languageCode: "en",
    ageLimit: 10,
    pageCount: 251,
    publisher: "Bloomsbury",
    publishedDate: "1998-07-02",
    seriesIndex: 2,
    seriesId: 6,
    rating: 4.7,
    totalReviews: 4800,
    coverUrl: "https://example.com/covers/harry-potter-2.jpg",
    previewUrl: null,
    downloadUrl: null,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-06T11:10:00Z"),
    updatedAt: new Date("2023-01-06T11:10:00Z"),
    createdByUserId: null,
  },
  // The Witcher (Andrzej Sapkowski)
  {
    id: 15,
    title: "The Last Wish",
    originalTitle: "Ostatnie życzenie",
    description: "A collection of short stories introducing Geralt of Rivia, a witcher, as he battles monsters and navigates human conflicts.",
    slug: "the-last-wish",
    isbn: "9780316029186",
    languageCode: "pl",
    ageLimit: 16,
    pageCount: 384,
    publisher: "superNOWA",
    publishedDate: "1993-01-01",
    seriesIndex: 1,
    seriesId: 7,
    rating: 4.7,
    totalReviews: 2200,
    coverUrl: "https://example.com/covers/the-last-wish.jpg",
    previewUrl: null,
    downloadUrl: null,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-07T13:00:00Z"),
    updatedAt: new Date("2023-01-07T13:00:00Z"),
    createdByUserId: null,
  },
  {
    id: 16,
    title: "Sword of Destiny",
    originalTitle: "Miecz przeznaczenia",
    description: "Another collection of Witcher stories, deepening Geralt’s relationships with Ciri and Yennefer in a world of destiny and danger.",
    slug: "sword-of-destiny",
    isbn: "9780316389709",
    languageCode: "pl",
    ageLimit: 16,
    pageCount: 400,
    publisher: "superNOWA",
    publishedDate: "1992-01-01",
    seriesIndex: 2,
    seriesId: 7,
    rating: 4.6,
    totalReviews: 2100,
    coverUrl: "https://example.com/covers/sword-of-destiny.jpg",
    previewUrl: null,
    downloadUrl: null,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-07T13:10:00Z"),
    updatedAt: new Date("2023-01-07T13:10:00Z"),
    createdByUserId: null,
  },
  // Standalone books
  {
    id: 17,
    title: "Good Omens",
    originalTitle: null,
    description: "A comedic novel by Neil Gaiman and Terry Pratchett about an angel and demon teaming up to prevent the apocalypse.",
    slug: "good-omens",
    isbn: "9780060853983",
    languageCode: "en",
    ageLimit: 14,
    pageCount: 432,
    publisher: "William Morrow",
    publishedDate: "1990-05-01",
    seriesIndex: 0,
    seriesId: null,
    rating: 4.8,
    totalReviews: 3000,
    coverUrl: "https://example.com/covers/good-omens.jpg",
    previewUrl: null,
    downloadUrl: null,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-08T15:00:00Z"),
    updatedAt: new Date("2023-01-08T15:00:00Z"),
    createdByUserId: null,
  },
  {
    id: 18,
    title: "Carrie",
    originalTitle: null,
    description: "Stephen King’s debut novel about a telekinetic teenager who unleashes her powers after being bullied.",
    slug: "carrie",
    isbn: "9780385086950",
    languageCode: "en",
    ageLimit: 16,
    pageCount: 199,
    publisher: "Doubleday",
    publishedDate: "1974-04-05",
    seriesIndex: 0,
    seriesId: null,
    rating: 4.3,
    totalReviews: 2500,
    coverUrl: "https://example.com/covers/carrie.jpg",
    previewUrl: null,
    downloadUrl: null,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-08T15:10:00Z"),
    updatedAt: new Date("2023-01-08T15:10:00Z"),
    createdByUserId: null,
  },
];