export const seriesData = [
  {
    id: 1,
    title: "Discworld: Death",
    slug: "discworld-death",
    description: "A sub-series of Discworld focusing on Death, a skeletal figure with a fondness for cats and curry, and his interactions with mortals, including his apprentice Mort and granddaughter Susan.",
    coverUrl: "https://example.com/covers/discworld-death.jpg",
    rating: 4.8,
    averageRating: 4.7,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-01T10:00:00Z"),
    updatedAt: new Date("2023-01-01T10:00:00Z"),
  },
  {
    id: 2,
    title: "Discworld: Witches",
    slug: "discworld-witches",
    description: "A sub-series of Discworld centered on the witches of Lancre, including Granny Weatherwax, Nanny Ogg, and Magrat Garlick, dealing with magic, folklore, and meddling in human affairs.",
    coverUrl: "https://example.com/covers/discworld-witches.jpg",
    rating: 4.9,
    averageRating: 4.8,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-02T12:00:00Z"),
    updatedAt: new Date("2023-01-02T12:00:00Z"),
  },
  {
    id: 3,
    title: "The Sandman",
    slug: "the-sandman",
    description: "A dark fantasy series by Neil Gaiman, following Dream of the Endless, exploring mythology, history, and human stories through a blend of horror, fantasy, and drama.",
    coverUrl: "https://example.com/covers/the-sandman.jpg",
    rating: 4.7,
    averageRating: 4.6,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-03T14:00:00Z"),
    updatedAt: new Date("2023-01-03T14:00:00Z"),
  },
  {
    id: 4,
    title: "The Dark Tower",
    slug: "the-dark-tower",
    description: "Stephen King's epic fantasy-western series, following Roland Deschain, the last gunslinger, on his quest for the Dark Tower, blending horror, sci-fi, and mythology.",
    coverUrl: "https://example.com/covers/the-dark-tower.jpg",
    rating: 4.6,
    averageRating: 4.5,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-04T16:00:00Z"),
    updatedAt: new Date("2023-01-04T16:00:00Z"),
  },
  {
    id: 5,
    title: "Echo Chronicles",
    slug: "echo-chronicles",
    description: "A fantasy series by Max Frei, set in the magical city of Echo, following Sir Max as he navigates detective mysteries and supernatural adventures.",
    coverUrl: "https://example.com/covers/echo-chronicles.jpg",
    rating: 4.5,
    averageRating: 4.4,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-05T09:00:00Z"),
    updatedAt: new Date("2023-01-05T09:00:00Z"),
  },
  {
    id: 6,
    title: "Harry Potter",
    slug: "harry-potter",
    description: "J.K. Rowling's iconic fantasy series about Harry Potter, a young wizard, and his adventures at Hogwarts, battling the dark wizard Voldemort.",
    coverUrl: "https://example.com/covers/harry-potter.jpg",
    rating: 4.9,
    averageRating: 4.8,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-06T11:00:00Z"),
    updatedAt: new Date("2023-01-06T11:00:00Z"),
  },
  {
    id: 7,
    title: "The Witcher",
    slug: "the-witcher",
    description: "Andrzej Sapkowski's fantasy series about Geralt of Rivia, a monster hunter with magical abilities, navigating a morally complex world.",
    coverUrl: "https://example.com/covers/the-witcher.jpg",
    rating: 4.7,
    averageRating: 4.6,
    isPublished: true,
    isVerified: true,
    createdAt: new Date("2023-01-07T13:00:00Z"),
    updatedAt: new Date("2023-01-07T13:00:00Z"),
  },
];