export const usersData = [
  {
    id: 1,
    email: "ledich19@gmail.com",
    emailVerified: false,
    passwordHash: "$2b$10$DLN.Jdh695zhaw5GgpX7iecqCFYFHVvISe1SlGSducl29jjeU073.",
    username: null,
    name: "dev",
    preferences: null,
    isAdmin: false,
    avatarUrl: null,
    bio: null,
    totalPoints: 0,
    totalReviews: 0,
    totalBooksRead: 0,
    lastLoginAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    id: 2,
    email: "user1@example.com",
    emailVerified: true,
    passwordHash: "$2b$10$DLN.Jdh695zhaw5GgpX7iecqCFYFHVvISe1SlGSducl29jjeU073.",
    username: "reader1",
    name: "User One",
    preferences: { theme: "dark", language: "en" },
    isAdmin: false,
    avatarUrl: "https://example.com/avatar1.png",
    bio: "Люблю читать фэнтези.",
    totalPoints: 120,
    totalReviews: 4,
    totalBooksRead: 12,
    lastLoginAt: new Date("2025-05-20T10:00:00Z"),
    createdAt: new Date("2025-01-10T08:00:00Z"),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    id: 3,
    email: "admin@example.com",
    emailVerified: true,
    passwordHash: "$2b$10$DLN.Jdh695zhaw5GgpX7iecqCFYFHVvISe1SlGSducl29jjeU073.",
    username: "admin",
    name: "Site Admin",
    preferences: { theme: "light", language: "ru" },
    isAdmin: true,
    avatarUrl: "https://example.com/admin.png",
    bio: "Администратор платформы.",
    totalPoints: 999,
    totalReviews: 99,
    totalBooksRead: 250,
    lastLoginAt: new Date("2025-05-21T12:00:00Z"),
    createdAt: new Date("2024-12-01T09:30:00Z"),
    updatedAt: new Date(),
    deletedAt: null,
  }
]