export const genreData = [
  { id: 1, name: "Fantasy" },
  { id: 2, name: "Science Fiction" },
  { id: 3, name: "Dystopian" },
  { id: 4, name: "Adventure" },
  { id: 5, name: "Romance" },
  { id: 6, name: "Contemporary" },
  { id: 7, name: "Mystery" },
  { id: 8, name: "Thriller" },
  { id: 9, name: "Horror" },
  { id: 10, name: "Paranormal" },
  { id: 11, name: "Historical Fiction" },
  { id: 12, name: "Historical Romance" },
  { id: 13, name: "Memoir" },
  { id: 14, name: "Biography" },
  { id: 15, name: "Self Help" },
  { id: 16, name: "Health" },
  { id: 17, name: "Travel" },
  { id: 18, name: "Guide / How-to" },
  { id: 19, name: "Families & Relationships" },
  { id: 20, name: "Humor" },
  { id: 21, name: "Children’s" },
  { id: 22, name: "Middle Grade" },
  { id: 23, name: "Young Adult" },
  { id: 24, name: "New Adult" },
  { id: 25, name: "LGBTQ+" },
  { id: 26, name: "Science" },
  { id: 27, name: "Philosophy" },
  { id: 28, name: "Religion" },
  { id: 29, name: "Spirituality" },
  { id: 30, name: "Poetry" },
  { id: 31, name: "Comics" },
  { id: 32, name: "Graphic Novel" },
  { id: 33, name: "Art" },
  { id: 34, name: "Cookbooks" },
  { id: 35, name: "True Crime" },
  { id: 36, name: "Politics" },
  { id: 37, name: "Economics" },
  { id: 38, name: "Education" },
  { id: 39, name: "History" },
  { id: 40, name: "Music" },
  { id: 41, name: "Psychology" },
  { id: 42, name: "Sociology" },
  { id: 43, name: "Technology" },
  { id: 44, name: "Business" },
  { id: 45, name: "Programming" },
  { id: 46, name: "AI / Machine Learning" },
  { id: 47, name: "Mathematics" },
  { id: 48, name: "Short Stories" },
  { id: 49, name: "Classics" },
  { id: 50, name: "Drama" },
  { id: 51, name: "Western" },
  { id: 52, name: "War" },
  { id: 53, name: "Anthology" },
  { id: 54, name: "Essay" },
  { id: 55, name: "Satire" },
];
